### ISSUE TITLE
random order?

### ISSUE THREAD

**Issue by oparoz** [nextcloud/gallery#104]
_From @ak1n on December 23, 2015 0:3_

Is there a way to display images in a random order rather than the date/name options listed on the wiki page in the sort section?

If the answer is presently no, could anyone perchance reference the area of code dealing with sorting? Would handling this simply involve randomizing a received file array (initially and then upon each completion of the full rotation)?

Thanks for any recommendations/thoughts in this regard!
##

_Copied from original issue: owncloud/gallery#480_

**Comment by oparoz** [comment]
> Is there a way to display images in a random order rather than the date/name options listed on the wiki page in the sort section?

Nope... Didn't think there was a need :)

> Would handling this simply involve randomizing a received file array (initially and then upon each completion of the full rotation)?

That's correct.

This returns the list of files:
https://github.com/owncloud/gallery/blob/5628f45fd2a4bd5371923e9ba82a178275514035/js/gallery.js#L67

For a quick hack, you could add your own sorting order at the end of the function by calling `Gallery.config.updateAlbumSorting`

But you will need to create a new "random" sorting type in here: https://github.com/owncloud/gallery/blob/5628f45fd2a4bd5371923e9ba82a178275514035/js/galleryutility.js#L185

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
