### ISSUE TITLE
icon-loading-dark visible when viewing small images

### ISSUE THREAD

**Issue by jaller94** [nextcloud/gallery#160]
### Steps to reproduce
1. Create an image with width or height less than 32px.
2. Upload it to your Nextcloud.
3. View the image in the gallery.
### Expected behaviour

Once the image is loaded, the icon-loading-dark should disappear.
### Actual behaviour

Even after the image is loaded, the icon-loading-dark is still visible and rotating in the background.
### Server configuration

**Operating system**: Linux 2.6.32

**Web server:** Apache

**Database:** mariadb 10.0.25

**PHP version:** 7.0.8

**Nextcloud version:** 10.0.0

**Gallery version:** 15.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 9.0.53

**Where did you install Nextcloud from:** nextcloud.com
### Client configuration

**Browser:** Firefox 45.1.1 / IE 11.0

**Operating system:** Windows 7

**Comment by oparoz** [comment]
Thanks I did notice it, but apparently had not files a bug.
It should be easy to fix for anybody who has worked with Javascript before as we should just hide the spinner once an image is shown.
