### ISSUE TITLE
Checkerboard behind transparent images not repeated but streched

### ISSUE THREAD

**Issue by jaller94** [nextcloud/gallery#161]
### Steps to reproduce
1. Upload a transparent image onto your Nextcloud.
2. View it in the Gallery app.
3. Hover it with your mouse/cursor.
### Expected behaviour

The CSS background image should be repeated so it becomes a checkerboard. This is defined here: https://github.com/nextcloud/gallery/blob/ee63a8aa5b2a3c35ac4779f39c5c19bbf7c6df55/css/slideshow.css#L28

![expected](https://cloud.githubusercontent.com/assets/10872136/18545771/d7176cca-7b3a-11e6-812f-61de1e068c36.png)
### Actual behaviour

The CSS background-image is streched.

A local style has been applied by some JavaScript, setting the background-size attribute. This causes the background image to be streched.
![actual](https://cloud.githubusercontent.com/assets/10872136/18545741/b97648da-7b3a-11e6-8197-aaa56f31945a.png)
### Server configuration

**Nextcloud version:** 10.0.0

**Gallery version:** 15.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 9.0.53

**Where did you install Nextcloud from:** nextcloud.com

**Comment by oparoz** [comment]
Thanks for the report. This is due to the library that we use which takes the original div and zooms in and out.
Hopefully this will be fixed once we change slideshow engine.

**Comment by skjnldsv** [comment]
Superseded by #540
