### ISSUE TITLE
Gallery shows no images/albums

### ISSUE THREAD

**Issue by fossxplorer** [nextcloud/gallery#163]
NC stable10. Tested with Gallery version stable10 and tar ball 10.0.1
I can see the sort, share etc button, but no albums at all. Tested on FF and Chrome.
Gallery works showing images inside Files though.

@oparoz

**Comment by fossxplorer** [comment]
The problem was files_odfviewer which showed up in the console when loading gallery app.
Disabling files_odfviewer fixes this issue.

**Comment by oparoz** [comment]
Thanks for the update!
