### ISSUE TITLE
Safety Issue: Thumbnails of pictures are not encrypted (default encryption module)

### ISSUE THREAD

**Issue by ManuelFDS** [nextcloud/gallery#167]
Bug report:
Safety Issue: Thumbnails of pictures are not encrypted (default encryption module)

Steps to reproduce:
1.  Activate default encryption module also for user folders
2. Upload pictures into user folder
3. View them with gallery
4. Access nextcloud data-folder on Server via sftp or ssh
5. View the thumbnails without decrypting routines. 

Expected behavior:

In case of user folder data encryption module turned on, I would expect that all thumbnails generated should be encrypted on the server, too.

Actual behaviour:

Thumbnails and Diashows are stored unencrypted on server in data-folder.

Server configuration:

**Operating system**: Webspace

**Web server:** Webspace

**Database:** MySQL

**PHP version:** 7

**cloud server:** Nextcloud 10.0.1

**cloud version:** (see admin page or version.php)

**Updated from an older installation or fresh install:** Updated from Nextcloud 9

**List of activated apps:**

**Comment by oparoz** [comment]
Since Gallery relies on the server to provide the previews, it's not something that we can fix. Please re-open in nextcloud/server if the issue hasn't been opened yet.
