### ISSUE TITLE
Generated previews are not shared

### ISSUE THREAD

**Issue by Glandos** [nextcloud/gallery#185]
### Steps to reproduce

1. Go to a gallery

### Expected behaviour

According to https://rullzer.com/nextcloud-11-preview-improvements.html previews should be shared. Using this application, previews seems to be stored in `data/appdata_5076f7a67458c/`. These thumbnails should be used by the gallery application. The file application seems to use that new system.

### Actual behaviour

Gallery is generating preview in data/<user>/thumbnails. This is inefficient since it regenerates, and takes up twice the disk space.

### Server configuration
<details>
<summary>Configuration</summary>

**Operating system**: Debian/testing

**Web server:** nginx

**Database:** PostgreSQL

**PHP version:** 7.0.13

**cloud server:** Nextcloud

**cloud version:** 11.0.0

**Updated from an older installation or fresh install:** updated from 10.0.1

**List of activated apps:**

<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - audioplayer: 1.3.1
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - direct_menu: 0.9.3
  - external: 1.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - previewgenerator: 1.0.1
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - documents
  - encryption
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - theming
  - user_ldap
  - user_saml

```

</details>
 
**The content of config/config.php:**

<details>
<summary>Config report</summary>

```
{
    "system": {
        "datadirectory": "\/media\/nas\/shares\/",
        "dbtype": "pgsql",
        "version": "11.0.0.10",
        "installedat": "1325338463.9158",
        "lastupdatedat": "1337694133.2558",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 1,
        "log_rotate_size": 10485760,
        "apps_paths": [
            {
                "path": "\/var\/www\/cloud.example.com\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/cloud.example.com\/nextcloud\/apps_writable",
                "url": "\/apps_writable",
                "writable": true
            }
        ],
        "instanceid": "5076f7a67458c",
        "maintenance": false,
        "theme": "",
        "singleuser": false,
        "trusted_domains": [
            "cloud.example.com"
        ],
        "mail_smtpmode": "php",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/run\/redis\/redis.sock",
            "port": 0
        },
        "forcessl": true,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "{mail.example.com\/imap\/tls\/readonly}"
                ]
            }
        ],
        "mail_from_address": "cloud",
        "mail_domain": "example.com"
    }
}
```

</details>

**Are you using external storage, if yes which one:** local folder

**Are you using encryption:** no

**Are you using custom gallery.cnf config files:** no

#### Web server error log

<details>
<summary>Web server error log</summary>

```
```
</details>

#### Cloud log

<details>
<summary>Cloud log</summary>

```
```
</details>

### Client configuration

**Browser:** Firefox 50.1

**Operating system:** Debian/unstable

#### Browser log

<details>
<summary>Browser log</summary>

```
```

</details>
</details>
 
## Feature request
<details>
<summary>Request</summary>

**User type**: Logged-in or public user

**User level**: Beginners, intermediate or advanced

### Sponsorship

 
**Are you a developer willing to implement this feature?**: yes/no

**Can you sponsor the development of this feature or do you know someone who can?**: yes/no

</details>

**Comment by rullzer** [comment]
Unfortunatly we were out of time to fix the gallery app. This will be tackled shortly

**Comment by Glandos** [comment]
Thanks for the reply. I'll leave this issue open, just in case some other people ask the same question, until a new release.

**Comment by timmikk** [comment]
Thanks for the info. I found this report when I was investigating why the preview loading in gallery app was still so slow even after the preview improvements. I have been waiting for this feature for years so maybe I can wait a bit longer ;). Anyway thanks for the great work!

**Comment by cowai** [comment]
Is there plans to backport this to NC 11 ? Or can I just use the master branch in NC11?

**Comment by oparoz** [comment]
It's a pretty big change, we only backport regressions or security fixes, so you should try master.

**Comment by rullzer** [comment]
Or wait for NC12 :wink:
