### ISSUE TITLE
Integrate OCR

### ISSUE THREAD

**Issue by adamlove86** [nextcloud/gallery#191]
It seems that OCR of images is working - it would be great to be able to integrate this into the official Gallery app. Even Google Drive can't do this yet, so would be a great advantage for you!
(https://github.com/janis91/ocr)

Running Ubuntu 16.04, Nextcloud 11, Gallery 16.0,0

## Feature request

**User type**: Logged-in or public user

**User level**: Beginners, intermediate or advanced

### Sponsorship

 
**Are you a developer willing to implement this feature?**: yes/no

**Can you sponsor the development of this feature or do you know someone who can?**: yes/no

**Comment by oparoz** [comment]
Could you fill the template in your OP to tell us a bit more about how it should work and why we should do it?

**Comment by linuxrrze** [comment]
Hint:

Nextant app also uses OCR on images (requires tesseract to be installed with solr).
So if the intention is to search for text contained in images, a solution may already be there

**Comment by adamlove86** [comment]
Thanks @linuxrrze, and apologies @oparoz - that is what I meant: being able to integrate the currently existing Nextant OCR function into the official Gallery app.

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.
