### ISSUE TITLE
Idea to use the PhotoFloat JSON/Javascript approach

### ISSUE THREAD

**Issue by kosli** [nextcloud/gallery#192]
I am using PhotoFloat (https://git.zx2c4.com/PhotoFloat/about/) for my private photo gallery and I love it's simple, but efficient approach for showing the pictures. Instead of dynamically rendered HTML pages, it uses client side JavaScript to access a simple JSON-based cache with all the information about the pictures, per directory. 

"A Web 2.0 Photo Gallery Done Right via Static JSON & Dynamic Javascript"

Perhaps a similar approach could be used to speed up the NextCloud Gallery.

**Comment by oparoz** [comment]
PhotoFloat would be a complete replacement and wouldn't be any faster. The speed issue comes from having to generate all the thumbnails.
