### ISSUE TITLE
Being able to choose compression quality

### ISSUE THREAD

**Issue by AngeloFrangione** [nextcloud/gallery#194]
## Feature request
**User type**: Logged In or not

**User level**: Beginners

### Description
Is there a way to choose the quality of the image preview compression ratio ? And even disable it ? I think not, I even tried to look into the code found nothing about it.

### Benefit / value
People can choose for the right compression ratio they want, more compression for BIG CPU/slow internet connection, less or no compression for users with little CPU and fast internet connection
 
**Are you a developer willing to implement this feature?**: yes but don't found where IPreview is located

**Can you sponsor the development of this feature or do you know someone who can?**: no

I think you need to stop testing your product under high end server with Xeon and 16 cores. Not everybody can afford that !
And if it's fast on a dual core Intel atom, imagine how fast it's on a Xeon ?

### Illustration
Here is htop when i load an album with the gallery:
![capture d ecran 2017-01-17 a 18 05 15](https://cloud.githubusercontent.com/assets/3856645/22030959/8487249e-dcdf-11e6-81de-422132ee1b53.png)
And it takes about 5 seconds for loading a thumbnail in the global photo view, and about 10 sec for viewing a single picture, when I try to view a single pictures all 4 cores are loaded about 100%

**Comment by oparoz** [comment]
Please open the issue in #nextcloud/server, because that's where previews are generated. It would require introducing a new config setting and would make it easier for low-powered devices to generate previews.
