### ISSUE TITLE
Upload dropdown broken 

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/gallery#197]
Since the new dropdown, the gallery app needs to fit the css guidelines.

![capture d ecran_2017-01-24_00-29-14](https://cloud.githubusercontent.com/assets/14975046/22227548/25b26fea-e1cc-11e6-9e16-08a2ecc4adf5.png)

**Comment by oparoz** [comment]
The dropdown works for me on 11.0.1. Which browser are you using?

**Comment by skjnldsv** [comment]
The new dropdown is implemented in nc12.
Backport has been merged for the next nc11 release nextcloud/server#3286

**Comment by oparoz** [comment]
Ah, thanks for the clarification.

**Comment by skjnldsv** [comment]
Well, this will become a nc11 issue as well on the next release :)

**Comment by MorrisJobke** [comment]
> Well, this will become a nc11 issue as well on the next release :)

@skjnldsv Could you fix it?

**Comment by skjnldsv** [comment]
@MorrisJobke Yes, just need some free time. This is the same as the newfileupload fix I did on the Files app :)
