### ISSUE TITLE
Add a share button to the large preview [$5]

### ISSUE THREAD

**Issue by oparoz** [nextcloud/gallery#20]
_From @oparoz on March 7, 2015 22:18_

We already have download, maybe it would be useful to have a "share" button there as well?
Clicking on it would reveal the usual dropdown and let people share that one picture via the usual means.

It's something I've seen on other slideshows, but I have no idea if this is really needed or if people would rather share the entire folder like it is now.
### Next steps
- [x] Share button
- [ ] A sidebar https://github.com/nextcloud/gallery/issues/118
- [x] Import sharing view from `core`

There is a [share API](https://docs.nextcloud.org/server/11/developer_manual/core/ocs-share-api.html), but using it in this app just means re-inventing the wheel, so we should use whatever is used in `core` and theme it
##

_Copied from original issue: owncloud/gallery#68_

**Comment by oparoz** [comment]
_From @deMattin on March 14, 2015 18:51_

It could be usefull in some (rare) situations - but normally I share single files from file app.
You tagged for user experience? I don't need this!
But it won't annoy me, if it would be there.

**Comment by oparoz** [comment]
It's all about making the life of users easier. You're in full screen mode and you see something you want to share, you don't want to have to quit the slideshow, go to Files, find the file and click share.

**Comment by oparoz** [comment]
_From @jancborchardt on March 17, 2015 11:47_

Yes – all actions which are available in the files list should also be available in the detail view. However (as I think I said in another issue as well) instead of bulky buttons up top, as nice grey text+icons on the bottom center. :)

**Comment by oparoz** [comment]
_From @jancborchardt on December 16, 2015 15:57_

Moving the actions from up top to a proper place is prerequisite for this: https://github.com/owncloud/gallery/issues/349

Also to fix the confusion: https://github.com/owncloud/gallery/issues/474

**Comment by oparoz** [comment]
_From @jospoortvliet on December 16, 2015 16:34_

Add commenting! for 9.0 ;-)

**Comment by oparoz** [comment]
_From @jancborchardt on December 16, 2015 19:7_

@jospoortvliet different issue ;) https://github.com/owncloud/gallery/issues/176

**Comment by oparoz** [comment]
Once we have a sidebar, we should be able to use the `core` share dialogue
https://github.com/owncloud/core/blob/master/core/js/sharedialogview.js

and get rid of our old share.js

**Comment by MorrisJobke** [comment]
@nextcloud/designers Do you have a nice idea how to integrate the sharing interface nicely into the slideshow, because it is quite bad UX if you have a picture opened and need to go back to the folder view find the correct picture and then be able to share it. Ideas? Basically the little sharing icon in the slideshow, but then? How could this look like? We have a quite big sharing menu and putting it straight in there is hard or doesn't really fit. :/

**Comment by MorrisJobke** [comment]
@rullzer This was planed to be included. Is it possible to load the side bar here?

**Comment by MorrisJobke** [comment]
@icewind1991 Haven't you worked on this as well?

**Comment by icewind1991** [comment]
Having the full sidebar will be a lot of work to get working properly so probably not in nc12 scope

**Comment by MorrisJobke** [comment]
> Having the full sidebar will be a lot of work to get working properly so probably not in nc12 scope

But the sharing interface is possible?

**Comment by rullzer** [comment]
@MorrisJobke my javascript skills are not developed enough to have the sidebar in gallery.

**Comment by oparoz** [comment]
We now have sharing via an additional button
