### ISSUE TITLE
Add a favicon for the Gallery app.

### ISSUE THREAD

**Issue by roipoussiere** [nextcloud/gallery#207]
## Feature request

**User type**: Logged-in **and** public user

**User level**: Beginners

### Description
Favicons are small icons displayed by the browser on tabs and bookmarks. There are different icons for NextCloud apps (Mails, calendar, etc.) but not for Gallery app.

### Benefit / value
Favicons are good for accessibility and user-experience!

In my case this is problematic as I use Nextcloud with small bookmarks for each app on my browser, without text, like this:

![nextcloud bookmarks](http://i.imgur.com/3iLYJle.png)

Here you can see there is no graphical difference between the *File* bookmark and the *Gallery* bookmark.

### Risk / caveats
There is no risks for this issue.

### Development

Edit: I am working on this.

**Comment by MarkelFe** [comment]
This may need to be closed due to automatic favicon generation
