### ISSUE TITLE
Gallery 16.0.0 bundled in Nextcloud 11 does not match 16.0.0 in Github master

### ISSUE THREAD

**Issue by benqrn** [nextcloud/gallery#214]
There are fixes made to the master in Github for Gallery that place previews in a common folder (appdata), but the version of Gallery bundled in a new install of Nextcloud 11 does not have these fixes.  NC11 and the master of Gallery in Github, both have the same version number of 16.0.0, which seems incorrect.

This was identified via this issue when using the preview generator plugin; https://github.com/rullzer/previewgenerator/issues/29

**Comment by oparoz** [comment]
It's true that we should update the release number after each release.

**Comment by benqrn** [comment]
Can you fix that then so it's clear the version in NC11 is different from the current latest version, then @rullzer can note in previewgenerator that a specific minimum version of Gallery is required for his app.
