### ISSUE TITLE
Loader icon (spinner) never stops when at top level of gallery

### ISSUE THREAD

**Issue by jelofson** [nextcloud/gallery#223]
## Bug report

When you are at the top level of your gallery and you click on the home button, the "loader" spinner appears and never goes away. As though it triggered an ajax request (files/list) and is waiting for a response, but there isn't one. The spinner appears and never stops. 

This is a minor issue for sure, but if it's a quick fix, then it would be good to squash it. I can start digging in the source to see where it is, but might take me some time. If someone wants to point me directly to the source files affected, I might be able to help.

### Steps to reproduce

1. Go to the gallery app
1. Click the "home" icon in the breadcrumb

### Expected behaviour
Nothing should happen if you are at the top level. Do not trigger the icon change when at the top level of the gallery since there is no xhr request.

### Actual behaviour

No xhr request is triggered, but the home icon gets the loading spinner over top. The spinner never stops.

### Server configuration

**Operating system**:
Linux (Ubuntu 16.04)
**Web server:**
Apache 2
**Database:**
MySQL
**PHP version:**
7
**cloud server:** Nextcloud or ownCloud
Nextcloud
**cloud version:** (see admin page or version.php)
11.0.2
**Updated from an older installation or fresh install:**
Fresh install
**List of activated apps:**

**Are you using external storage, if yes which one:** local folder, smb share, sftp, etc.
local
**Are you using encryption:** yes/no
no
**Are you using custom gallery.cnf config files:** yes/no
no
#### Web server error log
none

### Client configuration

**Browser:**
Safari
**Operating system:**
MacOS Sierra
#### Browser log
No issues in browser

**Comment by oparoz** [comment]
Thanks for the report. It has already been fix on master.

**Comment by jelofson** [comment]
Ack. Apologies....
