### ISSUE TITLE
Opening publicly shared folder with image-specific-link should open the image viewer

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/gallery#231]
I have the shared folder https://cloud.jancborchardt.net/s/fsfe-sticker and want to link to a specific file in it. I just opened one image and copied the URL https://cloud.jancborchardt.net/s/fsfe-sticker#//fsfe-sticker-mockup.jpg

The problem is that if you open that in another browser, the file parameter is ignored and only the folder is opened.

@nextcloud/gallery

**Comment by oparoz** [comment]
IIRC, this has nothing to do with Gallery. Files doesn't allow for this and it should be fixed there.

**Comment by jancborchardt** [comment]
Is that so @schiessle @nickvergessen @icewind1991? :)

**Comment by nickvergessen** [comment]
well there is `scrollto=` but we dont open editors/viewers by the URL, thats right.

**Comment by buchanan** [comment]
This works for me there may be something wrong with your url. My urls don't have two trailing slashes after the shared folder. From your example
[https://cloud.jancborchardt.net/s/fsfe-sticker#fsfe-sticker-mockup.jpg](https://cloud.jancborchardt.net/s/fsfe-sticker#fsfe-sticker-mockup.jpg) should work
[https://cloud.jancborchardt.net/s/fsfe-sticker#//fsfe-sticker-mockup.jpg](https://cloud.jancborchardt.net/s/fsfe-sticker#//fsfe-sticker-mockup.jpg) should not work

**Comment by jancborchardt** [comment]
@buchanan this is what my server gives me, so it should work without modification. :)

**Comment by buchanan** [comment]
This isn't the URL that your server should give you. I have not been able to duplicate this problem on a clean install. Could you post steps to reproduce the issue?
I believe it is most likely a mis-configuration with your web server(apache/nginx).

**Comment by jancborchardt** [comment]
Maybe it has something to do with the file being in a subfolder of a subfolder?
