### ISSUE TITLE
Change default path for thumbnails?

### ISSUE THREAD

**Issue by enoch85** [nextcloud/gallery#233]
Sorry if this is already posted in some documentation or somewhere, I couldn't find it anyway...

With a lot of users the thumbnails folders are getting big quickly, my question is; can you change the default path to store thumbnails like with the `data dir` in config.php?

cc @oparoz

**Comment by oparoz** [comment]
Thumbnails are managed by the server. Gallery only re-uses them.
I don't think it's configurable though. There is a folder in data which is created for shared items and thumbnails are stored there.
