### ISSUE TITLE
Display photospheres

### ISSUE THREAD

**Issue by sbrl** [nextcloud/gallery#234]
## Feature request

**User type**: Whoever can view images

**User level**: I don't understand what you mean by this, but the feature would be something that a beginner could use, and programming-wise, I'd rate it at an intermediate task

### Description
With the popularisation of modern smartphones, more and more people now have the ability to take so-called photospheres, which capture a 360 degree view of a person's surroundings - not unlike an image from google streetview. An example can be found on [this page](http://photo-sphere-viewer.js.org/).

Unfortunately, Nextcloud does not currently display them correctly - only displaying the full image, and not the pannable/zoomable photosphere. I suggest that this be added, so that users can view their photospheres in the Nextcloud gallery and when previewing photos 

### Benefit / value
It would be rather nice if I could view my photospheres straight in Nextcloud, since my operating system's photo viewer doesn't currently support photospheres. Since support it's particularly common in operating systems and desktop apps from what I can see at the moment, it would enable people to view their photospheres on their laptops, PCs, etc. when they couldn't before.

### Risk / caveats
I foresee that Nextcloud's current image viewer could potentially be broken with the addition of this feature.

In addition, it is possible that the large nature of some photospheres might cause the server to hang while it is downloaded by a slow connection, though this is only more likely due to the nature of photospheres - hardly specific to photospheres alone.

### Sponsorship

 
**Are you a developer willing to implement this feature?**: possibly. I'd need guidance on which part of the codebase I want, and it would have to wait until I have some free time in the late summer.

**Can you sponsor the development of this feature or do you know someone who can?**: I don't understand, so probably not :confused:

**Comment by jaller94** [comment]
This would likely be possible to acomplish with [A-Frame](https://aframe.io/). I already watched some of my photospheres with this locally.

To those familiar with developing Nextcloud extensions: Would this need to be part of the gallery app or could this be part of a separate extension and still feel 'native' in the gallery app?

**Comment by jaller94** [comment]
A-Frame is a JavaScript library and the camera is an object in a 3d world. Keyboard support should be no problem.

**Comment by jaller94** [comment]
A photosphere gallery is even one of their examples and described in the documentation.

https://aframe.io/docs/0.5.0/guides/building-a-360-image-gallery.html

An <a-scene/> (which is their root element) can reference to a canvas objects. This would be useful for embedding it into a Nextcloud application.

**Comment by oparoz** [comment]
This could be an interesting feature. You would need to select the a-frame viewer if you can identify that the image is a photosphere and have a special UI switch so that the standard navigation doesn't interfere.

**Comment by BloodyIron** [comment]
I really want to be able to see photospheres properly via nextCloud! I take them often, and it's for the experience at an event. Is this feasible? Can we get this baked in?

**Comment by BloodyIron** [comment]
So.... any chance we can get this? There's even more expanded multimedia content coming out like VR pictures and videos too. That'd be sweet to at least preview on nextCloud.

**Comment by R0Wi** [comment]
Hey guys, i've made a little Nextcloud-App for integrating photo-sphere-viewer.js. Check out my comment [here](https://github.com/nextcloud/gallery/issues/43#issuecomment-469022255)

**Comment by skjnldsv** [comment]
Superseded by https://github.com/nextcloud/gallery/issues/540 and https://github.com/nextcloud/files_photospheres/issues/27
