### ISSUE TITLE
Option to hide album vanished

### ISSUE THREAD

**Issue by oparoz** [nextcloud/gallery#239]
We used to have an entry in the + menu which allowed users to hide the current album.
It's not there any more, which means that the behaviour for loading menu plugin has changed in the server.

Any idea @nickvergessen @rullzer ?

**Comment by nickvergessen** [comment]
No idea, I don't touch such parts of JS code

**Comment by MorrisJobke** [comment]
Never have seen such an option. :/

**Comment by danxuliu** [comment]
I have tested this and I can see the _Hide Album_ entry in the _+_ menu when using both _stable12_ and _master_ branches. @oparoz Could you confirm if it is fixed for you too?

**Comment by MorrisJobke** [comment]
It is also available here -> closing for now

**Comment by oparoz** [comment]
Confirmed, thank you.
