### ISSUE TITLE
Move away from eventsource to allow browser caching

### ISSUE THREAD

**Issue by rullzer** [nextcloud/gallery#245]
Currently the loading of the thumbnails is done via the eventsource. While this loads very fancy it has the drawback that the thumbnails are not cached in the browser. So if you close the gallery app and come back later it will start fetching all thumbnails again.

This is painfull since the eventsource data is not cached and generates a stream of images that are all:
* fetched from disk
* parsed in memory to an image
* base64 encoded

I have a feeling that just loading the images (in whatever fancy javascript way to make it animate nicely) would save a lot of resources. As in a lot of cases the image is just cached (not checked) or we validate the etag which with the FileDisplayResponse is very fast and cheap.

@oparoz as discused
@icewind1991 as eventsource guru

**Comment by oparoz** [comment]
PR is in #242

**Comment by rullzer** [comment]
That is not true

**Comment by oparoz** [comment]
My mistake

**Comment by krombel** [comment]
Another argument for not using EventStream:
It would be possible to use the cache of the webserver (e.g. nginx) to not regenerate the thumbnails on every request (when not using pregenerated thumbnails) even when the browser has deleted its cache (or on another device)
