### ISSUE TITLE
Add Live Photo support 

### ISSUE THREAD

**Issue by scar86** [nextcloud/gallery#257]
## Feature request

**User type**: Logged-in

**User level**: Beginners

### Description

Apple just release an api to play live photos from a web browser 
https://developer.apple.com/live-photos/

### Benefit / value

Once live photos can be imported either from the iOS app or manually from a web browser it would be nice to be able to view/reproduce them on the gallery

**Comment by skjnldsv** [comment]
Superseded by https://github.com/nextcloud/gallery/issues/540
