### ISSUE TITLE
Clicking on the federated sharing info icon opens a wrong link

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/gallery#258]
The link goes to:
http://localhost/server//go.php?to=user-sharing-federated

And results in this:
![capture du 2017-04-27 15-35-09](https://cloud.githubusercontent.com/assets/925062/25485749/3f3e8f48-2b5f-11e7-9343-80c9cb42bdc9.png)

cc @schiessle @oparoz

**Comment by oparoz** [comment]
Where is this icon located?

**Comment by jancborchardt** [comment]
Sharing dialog, the »i« on the right of the share input:
![capture du 2017-04-27 15-39-08](https://cloud.githubusercontent.com/assets/925062/25485873/b188dc48-2b5f-11e7-9551-464fa0adb239.png)

**Comment by oparoz** [comment]
Is this still broken?

**Comment by MorrisJobke** [comment]
Tested and works now
