### ISSUE TITLE
Way too many labels in the Gallery app tracker

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/gallery#259]
There’s more issue labels than in the sever repository, and they have different colors … it’s kind of confusing.

Didn’t we have a tool to generalize all labels and milestones across repositories, where useful (like bug, enhancement, design, starter issue, to review etc)? cc @MorrisJobke @LukasReschke

**Comment by oparoz** [comment]
AFAIK, it's not mandatory for apps to match what server has. There are huge variations between repos. It's really up to the maintainers.
It's the same with the dev process, some repos merge to dev per example.
Do we really want to alienate devs by making them conform to what server is doing?

**Comment by MorrisJobke** [comment]
> Didn’t we have a tool to generalize all labels and milestones across repositories, where useful (like bug, enhancement, design, starter issue, to review etc)? cc @MorrisJobke @LukasReschke

Nope - feel free to write one. We only have this for the milestones.

**Comment by jancborchardt** [comment]
> AFAIK, it's not mandatory for apps to match what server has. There are huge variations between repos. It's really up to the maintainers.

I would say so that it roughly should be. Otherwise it feels like a whole new world if you just want to contribute to an app. It just makes it hard for no reason other than »The maintainer felt like it.« I do think some additional or different tags are warranted, but there’s a _lot_ which are not understandable. Like 5–100, »Feature request« (which is »enhancement« everywhere else), »in progress« which is »2. developing«, Nextcloud, Legacy, On hold etc which are just very specific.

> It's the same with the dev process, some repos merge to dev per example.

Which ones?

> Do we really want to alienate devs by making them conform to what server is doing?

We would alienate devs by making the process different in each repository. This is not only confusing to newcomers, but as you see also to people who know their way around the project very well. ;)
It’s not like we’re saying »do this or gtfo«, it’s just that we encourage the use of specific labels. And as far as I can see most repos just do it since we pretty much started out with the Github standard labels.

**Comment by oparoz** [comment]
> Otherwise it feels like a whole new world if you just want to contribute to an app

Sure, but community members often contribute to many different projects and they don't have the same labels or rules

>  It just makes it hard for no reason other than »The maintainer felt like it

But maintainers are usually the most important pieces, without them, a project can quickly die.

>  there’s a lot which are not understandable. Like 5–100

I would say. If you don't understand it, don't use it :). I'm sure people familiar with Scrum immediately know what it's about, others can ask. A wiki page would be nice of course.

> »Feature request« (which is »enhancement« everywhere else)

Not in my world. There is a key distinction between an enhancement and a feature request. The latter being the inclusion of a new feature, as opposed to a refinement to an existing feature. 
"I want to be able to perform this new action" vs "the way this panel works is confusing to users"

> »in progress« which is »2. developing«, Nextcloud, Legacy, On hold etc

Yes, a lot of these can be be removed. They exist for historical reasons.

> Which ones?

https://github.com/nextcloud/nextcloud-snap
And if you change the process and labels, there is a high chance to lose the maintainer and I understand his position. It has to be easy.

> And as far as I can see most repos just do it since we pretty much started out with the Github standard labels.

I don't think so. We have lots of variation on top of the default labels from Github in vm, calendar, nextant, etc.

It seems people find their rhythm and things still get done.

Overall I don't think it's that important. Newcomers don't have access to labels and it's usually the maintainer who picks them.

I do agree that a subset should be constant, like the 1-,2-,3-4, series. Maybe the first step should be to define that? Then maybe we can write instructions on how to include them via a couple of command lines.

**Comment by jancborchardt** [comment]
> I do agree that a subset should be constant, like the 1-,2-,3-4, series. Maybe the first step should be to define that? Then maybe we can write instructions on how to include them via a couple of command lines.

Yup, that’s the main point. If we don’t ever say »heya, best use these labels for a start« of course no one is gonna do it by themselves.


> Not in my world. There is a key distinction between an enhancement and a feature request. The latter being the inclusion of a new feature, as opposed to a refinement to an existing feature.
> "I want to be able to perform this new action" vs "the way this panel works is confusing to users"

This is not how we treat it in the server and everywhere else. Every issue is at least tagged with either »bug« or »feature«.

»I want to be able to perform this new action« is always »feature«.
»the way this panel works is confusing to users«, depending on which degree, either gets »bug & design« if it doesn’t give feedback or could be seen as a bug, or »feature & design« if there needs to be some major restructuring for it to be improved.

**Comment by oparoz** [comment]
Removed unnecessary labels.
