### ISSUE TITLE
Sharing doesn't work in gallery view.

### ISSUE THREAD

**Issue by Milo-W** [nextcloud/gallery#263]
### Steps to reproduce

1. Go to gallery view
1. Click the share button
1. Nothing happens when you input an e-mail, choose options, etc. NOTHING. Just the "loading" circle at the end of the form but no action whatsoever.

### Expected behaviour
Well, I should get a solid e-mail with a great gallery view link, right?

### Actual behaviour
Nothing happens.

### Server configuration
The best in the world. It doesn't matter here, anyway.

Latest Nextcloud (stable).

List of apps out of the box.

No, I don't have access to sudo and it's a stupid idea to make people sudo something. This way it's impossible to install Nextcloud on a shared hosting or even a managed VPS where they don't give you sudo. And that's another idea: why don't you remove this idiotic occ, leave it to the ownclouders, let them "have fun" with such an idiotic idea.

Everything is normal, I'm not listing anything here (config.php? Are you kidding me?).

![heh](https://cloud.githubusercontent.com/assets/13204535/25718348/f7a3fc16-3105-11e7-806e-c8372dfe8d3d.jpg)

**Comment by oparoz** [comment]
Thanks for the report. It has been fixed and will be available in Nextcloud 12.

**Comment by Milo-W** [comment]
Hmmm wasn't it supposed to be available in Nextcloud... 11? Did you edit this?
