### ISSUE TITLE
Social sharing in gallery slide show share dialog

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/gallery#267]
* include the social sharing in the slide show 

cc @rullzer @icewind1991 @oparoz

**Comment by MorrisJobke** [comment]
followup to #266

**Comment by oparoz** [comment]
The 3 dots are currently missing. Users cannot share on social media from the slideshow like they can from the Files app.

**Comment by oparoz** [comment]
Fixed in https://github.com/nextcloud/gallery/pull/254
