### ISSUE TITLE
Generated URL when sharing link from slideshow is wrong

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/gallery#268]
* open a picture
* click on the share button
* share by link
* expected: link like `https://example.org/s/DmI41l2VZD8qeQl`
* actual: `https://example.org/apps/undefined/s/DmI41l2VZD8qeQl`

cc @icewind1991 @rullzer @oparoz

**Comment by MorrisJobke** [comment]
followup to #266

**Comment by rullzer** [comment]
I can't reproduce this... link looks fine here...

**Comment by MorrisJobke** [comment]
I just checked out master and tried again:

<img width="503" alt="bildschirmfoto 2017-05-16 um 12 50 41" src="https://cloud.githubusercontent.com/assets/245432/26120419/50386554-3a36-11e7-920b-b8c425e5d2d5.png">

**Comment by rullzer** [comment]
@MorrisJobke I still can't. Could you try to find where this is generated for you?

**Comment by oparoz** [comment]
Got the same problem with the "share with social media" apps
