### ISSUE TITLE
fullscreen change while sharing

### ISSUE THREAD

**Issue by mind22** [nextcloud/gallery#272]
### Steps to reproduce

1. Open Gallery + Press on a picture
2. Choose sharing symbol in the right top corner
3. search for any name with an "f"

### Expected behaviour
Normal searching for email/contacts etc.

### Actual behaviour
Every time you press an "f" in the search field, the gallery preview changes to fullscreen

### Server configuration

**Operating system**: Ubuntu 16.04.02 LTS

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.0.15

**cloud server:** Nextcloud 12 beta 3

**Comment by oparoz** [comment]
Good catch...

**Comment by MorrisJobke** [comment]
Fixed in #371
