### ISSUE TITLE
Map Exif GPS gallery

### ISSUE THREAD

**Issue by Kapu06** [nextcloud/gallery#274]
## New feature

Hi, I would like to know if you're working on a feature that would allow users to:

 * push pictures to directories
 * get GPS exif data from these pictures
 * make these pictures appear on a map (local umap or mapbox for example?).
 * share this map

If not, I'm new in JS, php, leaflet, and I don't know where to start to create this kind of feature and integrate it inside Nextcloud. Maybe is there already a similar open-source project which could be a good start to read/understand.
And I'm also newbie to github so sorry if it's not the good channel to talk about this.

And thank you for your work =)

**Comment by skjnldsv** [comment]
cc  @eneiluj you already do that in maps, right?
