### ISSUE TITLE
Controls for next/previous and autoplay or navigation via keyboard don't work

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/gallery#275]
Check it out on https://cloud.nextcloud.com/apps/gallery/s/0WDHAi9p5n0JSew# 

- Previous/next don't work neither via buttons nor arrow keys
- Neither does the autoplay/slideshow mode

cc @nextcloud/gallery

**Comment by oparoz** [comment]
Duplicate of https://github.com/nextcloud/gallery/issues/270
