### ISSUE TITLE
The sharing functionality far from good.

### ISSUE THREAD

**Issue by Milo-W** [nextcloud/gallery#280]
Nextcloud 12.

OK, so it can share a gallery view. At last! WOW...

BUT.

The sharing can't be a "input an e-mail, it shares automatically" feature.
There NEEDS to be a CallToAction button. You input an e-mail, you add options and then, somewhere at the bottom of this area, there should be a "share" button"!
If you add a wrong e-mail, it shares right away! This is just idiotic.

Please, can you add a UX Designer to the team or something? You can't have programmers design the interface because this is UNUSABLE. Also, the sorting options are in an idiotic position.

You don't need much to have a decent solution but at the moment this is like the beginning of the 2000s. If you want to achieve something with Nextcloud, you NEED to build a proper product.

**Comment by oparoz** [comment]
@nextcloud/designers

**Comment by jospoortvliet** [comment]
Please try to be polite, it's just software.

The design without a separate dialog with a bunch of options and a big share button is very deliberate and certainly not done by programmers but by our design team. It was decided to keep things simple, rather than overloading the user with options, and has been usability tested.

It is the same as in the sidebar in the files app, by the way.

I realize that it isn't what some users expect, being used to more complicated dialogs in other software, so perhaps it might make sense to follow that design pattern but that would have to be discussed, not done on a whim because somebody doesn't like it.

**Comment by Milo-W** [comment]
Yeah, but it's annoying. Plus, I had written about this before and this is not even close from that.

YOU CAN'T have an action just at the moment of finishing writing an e-mail address. Simply can't. There should be a slight pause in the user's action, and additional, actual button. It's just good practices. Look - even the live search from google is not copied over different GUIs.

I hate this BS - "simple", etc. You don't have to overload. You lack substantial standards in the GUI here.
You can be simple. You added "can add/delete/something" under additional options and THAT IS simple but there needs to be a CTA when you enter an e-mail.

Don't tell me users or me or someone is used to more complicated dialogs. This is not the case here. You lack basic UX knowledge and judgment and this results in this functionality being utilized with a frustrating element of GUI.

You know, I really don't feel like my presenting solid arguments towards best practices will change anything. I can see that it's mostly programmers who rule this script in an authoritarian way.
I bet you don't give a heck about good practices, or rules of usability, like heuristics, etc.
In fact, if you are such mastahs of development, you should know right away about the way forms should be organized. You don't need live action here as - just as I said before - writing an improper e-mail from memory or wanting to edit it - will result in a wrong e-mail getting the notification. This is just misleading, bad.

Also, I had written about this in some other post and the way it's been "debugged" is just outrageous.

**Comment by MorrisJobke** [comment]
Just a little sidenote: I really love to work on something if I get shouted at. It is super motivational. ❤️ Thanks for this nice rant - now I immediately will fix this for free for you within the next hour. 🚶 

/irony

Nevertheless we like feedback and will try to enhance were possible. We also have a "rework the overall sharing UX" on our todo list, but there are also 1000 other little things and we haven't gotten to this, yet.

**Comment by Milo-W** [comment]
You know, this was the second time I mentioned this really hard bug and it just amazes me that it hasn't been taken care of. And as for Nextcloud, I would say this is really something really basic and very very important. Sharing a gallery? How long did people need to wait for the gallery view to be shared? It still doesn't work good.
Sorry but my credo is: whatever you do, do it the best way you can.

My attitude reflects the way I'm disgusted with this functionality. You want to create a great script? Reach for the great levels, not some medium stuff.

**Comment by enoch85** [comment]
@Milo-W Can you provide the code to make this happen? One of the greatest things with open source is that if you don't like something, or want to improve on a function, you can create a PR and fix it yourself.

Much better the spitting your disgust over the functionality IMHO.

**Comment by Milo-W** [comment]
I'm not a coder/programmer.
More of a GUI/UX/GFX.

**Comment by jospoortvliet** [comment]
Note that it doesn't just share when you enter an email address. It shares when you CLICK the email address or hit 'enter'. That is materially different from type-ahead.

And yeah, your tone is absolutely abysmal - I'm guessing you often find projects ignore your input. Consider it might have to do with you and how you communicate, not all the other projects.

It is pretty insulting to just assume this was mashed up by a developer without a clue about design while we have some highly acclaimed UX design people on board - the type that gives keynotes at events and organizes design workshops and has over 10-15 years experience. I am not a designer myself and have little opinion on this - I just leave it to the experts.

Which you don't seem to be, at least - I expect an U/X expert to know what they're talking about and be able to communicate that...

**Comment by oparoz** [comment]
@Milo-W - Reporting issues is a good first step, but if you're using the software and have expertise, it would really help if you could work with the team designing the software by proposing specs, along with mock-ups. Having a clear, common direction helps get coders on board to help fix things.

**Comment by jancborchardt** [comment]
> Please, can you add a UX Designer to the team or something? You can't have programmers design the interface because this is UNUSABLE. Also, the sorting options are in an idiotic position.

Alright.

> I'm not a coder/programmer.
> More of a GUI/UX/GFX.

Can you provide a mockup of how you think it would be good?

**Comment by jospoortvliet** [comment]
While there's plenty to improve with the sharing dialog I'm not counting on constructive feedback or a useful discussion here. I'll close. Anyone who has mockups or a list of, say, requirements, usecases, analysis of problems with the current dialog or other valuable input, please, feel free to re-open!
