### ISSUE TITLE
Duplicate feature lines in the details sharing tab

### ISSUE THREAD

**Issue by jzawer** [nextcloud/gallery#300]
### Steps to reproduce

1. Go to files and open picture details view.
2. Share picture.
3. Without closing details view, click on picture name to expand.
4. Click on share icon.
5. Close picture preview.

### Actual behaviour
If detail views was open and in sharing tab, after you close picture preview, you can see duplicate lines.

### Expected behaviour
When image preview is open i want to share picture too, but i can't do because when i have open picture preview and try to share image the list don't load in correct site and if i add new groups or users i get error from server.

### Server configuration

**cloud server:** Nextcloud or ownCloud Nexcloud

**cloud version:** (see admin page or version.php) 12

**Updated from an older installation or fresh install:** fresh install

**Browser:** Chrome

**Operating system:** W10

picture preview with sharing list open.
![vistaprevia](https://user-images.githubusercontent.com/15221566/28380106-5dce9492-6cb6-11e7-9989-7834f164880a.png)

Duplicated lines in the details sharing tab.
![duplicatedlines](https://user-images.githubusercontent.com/15221566/28380128-71a943ea-6cb6-11e7-883e-2409a3935fb2.png)

**Comment by MorrisJobke** [comment]
Fixed with #370
