### ISSUE TITLE
nextcloud 12 occ gallery don't exist. this is lie application is installed and worked

### ISSUE THREAD

**Issue by peturbg** [nextcloud/gallery#305]
hi guys.
the first time nextcloud 12 release i install it and today i start looking my photos and when i start looking them it didn't load the preview. So i write:

sudo -u www-data php /var/mydomain/occ gallery:create-thumbnails --all
and it comment me
[Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "gallery" namespace.
in my nextcloud i have gallery. So i check it with:
 sudo -u www-data php /var/mydomain occ  app:check-code gallery
 and it comment:
Analysing /var/mydomain/apps/gallery/lib/Middleware/EnvCheckMiddleware.php
 1 errors
    line  155: OC_User - Static method of private class must not be called
Deprecated field available: shipped => true
App is not compliant

Then i write this:

sudo -u www-data php /var/mydomain/occ  app:check-code gallery -vvv
Analysing /var/mydomain/apps/gallery/appinfo/app.php
 0 errors
Analysing /var/mydomain/apps/gallery/appinfo/routes.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Environment/EnvironmentException.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Environment/Environment.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Environment/NotFoundEnvException.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Controller/ConfigPublicController.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Controller/ConfigApiController.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Controller/PageController.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Controller/PreviewController.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Controller/FilesApiController.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Controller/PathManipulation.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Controller/Preview.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Controller/Files.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Controller/HttpError.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Controller/PreviewApiController.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Controller/Config.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Controller/PreviewPublicController.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Controller/ConfigController.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Controller/FilesController.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Controller/FilesPublicController.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Http/ImageResponse.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Service/Base64Encode.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Service/SearchFolderService.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Service/ThumbnailService.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Service/ConfigService.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Service/ServiceException.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Service/SearchMediaService.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Service/InternalServerErrorServiceException.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Service/PreviewService.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Service/NotFoundServiceException.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Service/Service.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Service/DownloadService.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Service/ForbiddenServiceException.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Service/FilesService.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/AppInfo/Application.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Middleware/CheckException.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Middleware/EnvCheckMiddleware.php
 1 errors
    line  155: OC_User - Static method of private class must not be called
Analysing /var/mydomain/apps/gallery/lib/Middleware/CheckMiddleware.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Middleware/SharingCheckMiddleware.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Config/ConfigValidator.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Config/ConfigParser.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Config/ConfigException.php
 0 errors
Analysing /var/mydomain/apps/gallery/lib/Utility/EventSource.php
 0 errors
Analysing /var/mydomain/apps/gallery/templates/part.linkerror.php
 0 errors
Analysing /var/mydomain/apps/gallery/templates/part.content.php
 0 errors
Analysing /var/mydomain/apps/gallery/templates/part.internalservererror.php
 0 errors
Analysing /var/mydomain/apps/gallery/templates/part.filenotfounderror.php
 0 errors
Analysing /var/mydomain/apps/gallery/templates/index.php
 0 errors
Analysing /var/mydomain/apps/gallery/templates/slideshow.php
 0 errors
Analysing /var/mydomain/apps/gallery/templates/authenticate.php
 0 errors
Analysing /var/mydomain/apps/gallery/templates/public.php
 0 errors
Mandatory field available: id => gallery
Mandatory field available: name => Gallery
Mandatory field available: description => Media gallery for Nextcloud with the following features:

                - Support for large selection of media types (depending on server setup)

                - Upload and organise images and albums straight from the app

                - Large, zoomable previews which can be shown in fullscreen mode

                - Sort images by name or date

                - Per album design, description and copyright statement

                - A la carte features (external shares, browser svg rendering, etc.)

                - Image download straight from the slideshow or the gallery

                - Switch to Gallery from any folder in files and vice-versa

                - Ignore folders containing a ".nomedia" file

                - Browser rendering of SVG images (disabled by default)

                - Native SVG support

                - Mobile support

                Provides a dedicated view of all images in a grid, adds image viewing capabilities to the
                files app and adds a gallery view to public links.
                Compatible with Firefox, Chrome and Internet Explorer 11

Mandatory field available: licence => AGPL
Mandatory field available: author => Olivier Paroz, Robin Appelman
Optional field available: version => 17.0.0
Optional field available: namespace => Gallery
Optional field available: category => ["Multimedia","Multimedia"]
Optional field available: documentation => {"user":"https:\/\/github.com\/nextcloud\/gallery\/blob\/master\/README.md","admin":"https:\/\/github.com\/nextcloud\/gallery\/blob\/master\/README.md","developer":"https:\/\/github.com\/nextcloud\/gallery\/wiki"}
Optional field available: website => https://github.com/nextcloud/gallery
Optional field available: bugs => https://github.com/nextcloud/gallery/issues
Optional field available: repository => {"@attributes":{"type":"git"},"@value":"https:\/\/github.com\/nextcloud\/gallery.git"}
Optional field available: dependencies => {"php":{"@attributes":{"min-version":"5.6","max-version":"7"}},"nextcloud":{"@attributes":{"min-version":"11","max-version":"12"}}}
Optional field available: default_enable =>
Deprecated field available: shipped => true
Optional field available: remote => []
Optional field available: public => []
Optional field available: types => []
Unused field available: repair-steps => {"install":[],"pre-migration":[],"post-migration":[],"live-migration":[],"uninstall":[]}
Unused field available: background-jobs => []
Unused field available: two-factor-providers => []
Unused field available: commands => []
Unused field available: activity => {"filters":[],"settings":[],"providers":[]}
App is not compliant

**Comment by oparoz** [comment]
Hello, where did you read that this command was available?

**Comment by peturbg** [comment]
hi
in version 11.x one time i use sudo -u www-data php /var/mydomain/occ gallery:create-thumbnails --all
occ gallery:create-thumbnails and it recreate all my preview. Now when i upgrade to nextcloud 12 the first day nextcloud 12 when public release was release i install it, and yestarday i try see my pictures and i see there is pictures preview don't load, include it stop there. In nextcloud version 11 all my photo was loading. So nobody help me and i seek for the command and i find it in internet. So man, put again in nextcloud version 12 gallery and when preview fail to load, this command to work: occ gallery:create-thumbnails --all
How i say this command was existed in nextcloud 11.

In meantime how can i recreate gallery preview.

**Comment by oparoz** [comment]
Hello, this command has never existed as part of Gallery. The only way to generate previews is to use this command: `./occ preview:pre-generate`
