### ISSUE TITLE
Expiration date chooser is not shown

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/gallery#313]
* open a image in the slideshow mode
* click on the top right icon to share the file
* click on "Share by link"
* click on "Set expiration date"
* actual: expiration date calendar widget is not shown
* expected: expiration date calendar widget should be shown

cc @oparoz 

Does someone from @nextcloud/javascript want to look into this?

**Comment by MorrisJobke** [comment]
@ChristophWurst @blizzz @rullzer @danxuliu Volunteers?

**Comment by danxuliu** [comment]
Fix is in #349
