### ISSUE TITLE
Share to user broken in slideshow

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/gallery#314]
* open a image in the slideshow mode
* click on the top right icon to share the file
* type a name into the share field
* wait for the autocomplete dropdown
* click on a name or select a name with cursors and press enter
* actual: drop down closes without sharing
* expected: the file should be shared to that user

cc @oparoz 

Does someone from @nextcloud/javascript want to look into this?

**Comment by MorrisJobke** [comment]
I just noticed that the file is properly shared to the user, but that this is not visible in the UI. Just close the slideshow and check the share entry in the files sidebar for that file. 😉

**Comment by danxuliu** [comment]
I have tested this using the current _master_ branch and I can see the avatar and name of the user with the _Can share_, _Can edit_... checkboxes in the share drop down. @MorrisJobke Could you confirm if it is fixed for you too?

**Comment by MorrisJobke** [comment]
I can't see the avatar and name (tested with Chrome and Safari):

![bildschirmfoto 2018-01-08 um 15 35 24](https://user-images.githubusercontent.com/245432/34675330-9bc666ac-f489-11e7-9fbd-e1aea3ea8c30.png)


support ticket: #96836

**Comment by danxuliu** [comment]
It works fine for me with latest _master_ branch of both server and gallery and both in Firefox and in Chromium. No idea what is going on here :-/

Firefox:
![gallery-share-firefox](https://user-images.githubusercontent.com/26858233/34682645-d772a98e-f49f-11e7-87b5-ba3604b74bc9.png)

Chromium:
![gallery-share-chromium](https://user-images.githubusercontent.com/26858233/34682659-dd1bb402-f49f-11e7-8195-bafa581d1300.png)

**Comment by MorrisJobke** [comment]
Right - works now here as well

**Comment by MorrisJobke** [comment]
Fixed with #370
