### ISSUE TITLE
gallery is empty

### ISSUE THREAD

**Issue by kreutpet** [nextcloud/gallery#319]
### Steps to reproduce

1. installed gallery app from github
2. enable gallery in admin
3. login as user and open gallery app
4. gallery window is empty
5. open admin ->logging

### Expected behaviour
open gallery shouldshow pictures

### Actual behaviour
gallery windows is empty and error message is logged

Error | gallery | Could not find resource file "/cloud/apps/gallery/js/merged.js"

### Server configuration

**Operating system**: 
 Ubuntu 16.04.3 LTS

**Web server:**
 Apache/2.4.18 (Ubuntu)

**Database:**
mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64) using  EditLine wrapper

**PHP version:**
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )

**cloud server:** Nextcloud or ownCloud
Nextcloud

**cloud version:** (see admin page or version.php)
11.0.4 (stable)
**Updated from an older installation or fresh install:**
migrated from owncloud and upgraded then to version 11
gallery app folder clean and fresh install from github
Gallery 18.0.0

**List of activated apps:**

<details>
<summary>App list</summary>

Enabled:
  - activity: 2.4.1
  - audioplayer: 2.1.0
  - bookmarks: 0.10.1
  - calendar: 1.5.4
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - documents: 0.15.0
  - external: true
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.4
  - nextcloud_announcements: 1.0
  - notes: 2.3.1
  - notifications: true
  - onlyoffice: 1.1.4
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - files_accesscontrol
  - files_automatedtagging
  - user_external
  - user_ldap
  - user_saml

</details>

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "oc8tlek3t7l6",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.10",
            "kreutzer.asuscomm.com"
        ],
        "datadirectory": "\/var\/www\/cloud\/data",
        "overwrite.cli.url": "https:\/\/192.168.1.10\/cloud",
        "htaccess.RewriteBase": "\/cloud",
        "dbtype": "mysql",
        "version": "11.0.4.1",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "log_type": "file",
        "logfile": "\/var\/log\/cloud.log",
        "loglevel": "2",
        "mail_from_address": "kreutzer.peter",
        "mail_smtpmode": "smtp",
        "mail_domain": "gmail.com",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "appstore.experimental.enabled": true,
        "updatechecker": false,
        "updater.release.channel": "stable",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl"
    }
}

<details>
<summary>Config report</summary>

</details>

**Are you using external storage, if yes which one:** local folder, smb share, sftp, etc.
googledrive
**Are you using encryption:** yes/no
no
**Are you using custom gallery.cnf config files:** yes/no
no
#### Web server error log

<details>
<summary>Web server error log</summary>

</details>

#### Cloud log

<details>
<summary>Cloud log</summary>

{"reqId":"Av+0xHDfi0PT\/x41ZT1J","remoteAddr":"108.171.129.188","app":"gallery","message":"Could not find resource file \"\/cloud\/apps\/gallery\/js\/merged.js\"","level":3,"time":"2017-09-19T18:04:09+00:00","method":"GET","url":"\/cloud\/apps\/gallery\/","user":"myuser","version":"11.0.4.1"}
{"reqId":"++g8D\/MwjSY0ot0Zj+\/f","remoteAddr":"108.171.129.188","app":"gallery","message":"Could not find resource file \"\/cloud\/apps\/gallery\/js\/scripts-for-file-app.js\"","level":3,"time":"2017-09-19T18:04:10+00:00","method":"GET","url":"\/cloud\/apps\/files\/","user":"myuser","version":"11.0.4.1"}</details>

### Client configuration

55.0.3 (32-Bit)

windows 7 sp1 64bit

#### Browser log

<details>
<summary>Browser log</summary>

</details>

**Comment by oparoz** [comment]
> fresh install from github Gallery 18.0.0

Did you track the stable11 branch?

**Comment by kreutpet** [comment]
ohhh yes that did the trick.
Sorry for that
