### ISSUE TITLE
Thumbnail overview doesn't work in federated folders

### ISSUE THREAD

**Issue by devz3r0** [nextcloud/gallery#322]
### Steps to reproduce

1. install nextcloud A and gallery
2. install nextcloud B and gallery
3. send a federation sharing from NC B to A with full permission
4. add that folder on A with a picture in it (so you see user@server next to the foldername)
5. open the folder and set it to the thumbnail view

### Expected behaviour
the thumbnail view of the pictures

### Actual behaviour
Exception: The owner has placed a restriction or the storage location is unavailable
the picture itself is open and viewable via filebrowser.

### Server configuration
Nextcloud 12.0.3 on both devices

**Operating system**:
ubuntu on device A and debian on device B with php 7

**Web server:**
Apache 2.4 on both
**Database:**
maria db 10

**PHP version:**
7
**cloud server:** Nextcloud or ownCloud
nextcloud
**cloud version:** (see admin page or version.php)
12.0.3
**Updated from an older installation or fresh install:**
updated

**Comment by oparoz** [comment]
Please read https://github.com/nextcloud/gallery/wiki/Gallery-configuration and let me know if enabling external shares fixes this for you.

**Comment by devz3r0** [comment]
sorry for the delay, I am in India so I only have a bad access to the test instances, I am back about 4th November, I will give you a review then.

**Comment by devz3r0** [comment]
so I am at home again and tried it out, and yes that fixed it.
Thanks
