### ISSUE TITLE
Three dots menu visible in slideshow sharing dialog

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/gallery#345]
* open image in slideshow
* click on the share icon
* actual: the three dots are visible at the bottom of the drop down
* expected: the three dots are not visible

![bildschirmfoto 2018-01-04 um 11 20 44](https://user-images.githubusercontent.com/245432/34559349-caf16c92-f141-11e7-9c77-87cecb5ddc26.png)

Comment by @danxuliu:

> This is caused by "#linkTextMore" not being hidden when the dropdown is created; it happens in current master too.

@danxuliu Could you have a look at this?

**Comment by danxuliu** [comment]
>  Could you have a look at this?

Yes, I was on it ;-)
