### ISSUE TITLE
Add comments to slideshow

### ISSUE THREAD

**Issue by oparoz** [nextcloud/gallery#35]
_From @oparoz on June 21, 2015 19:31_

Once comments [are implemented in 9.0](https://github.com/owncloud/core/issues/16328), we will be able to add them to the slideshow.
- [x] Comments in `core`
- [ ] ~~Files sidebar in slideshow https://github.com/owncloud/gallery/issues/548~~ Design a custom sidebar #549 
- [ ] Enable comments
##

_Copied from original issue: owncloud/gallery#176_

**Comment by oparoz** [comment]
Sidebar is a pre-requisite: https://github.com/owncloud/gallery/issues/548

**Comment by oparoz** [comment]
#548 will probably never happen, so we can't get the whole commenting system "for free", but what we could do is maybe show comments read-only?
The main drawback is that the Gallery sidebar won't look and work the same as the one in Files, but this is expected since that has not been designed to be shared.

@jospoortvliet @jancborchardt

**Comment by pwFoo** [comment]
Looks like we have to use gallery without comments? ☹️

**Comment by jancborchardt** [comment]
@pwFoo sorry about that, we are busy with other things at the moment. :) What do you think about the grid view of files, where in the right sidebar you have comments?

**Comment by pwFoo** [comment]
Short question. Is it just slideshow without comments? Single image view with comments? Because that should be fine too for me...

Just searching for a gallery with comments for single images by registered users.

**Comment by pwFoo** [comment]
@jancborchardt 
Looks like comments not implemented for single images?

**Comment by jancborchardt** [comment]
Please note the slideshow component of the Gallery app will be replaced with the new [Viewer app](https://github.com/nextcloud/viewer).
