### ISSUE TITLE
Main loading icon is not shown properly in gallery

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/gallery#351]
When the gallery is opened [a loading icon is shown](https://github.com/nextcloud/gallery/blob/b11be474139d5b92da3212634518756856b90186/js/app.js#L37) before the images are started to be loaded.

In Firefox the icon is cropped, although in Chromium it is fully shown. However, in both cases the icon should appear at the middle of the screen like in the _Files_ app instead of near the top.

Firefox:
![gallery-loading-firefox](https://user-images.githubusercontent.com/26858233/34646701-33ca1622-f36f-11e7-9b39-5d1be6ee9032.png)

Chromium:
![gallery-loading-chromium](https://user-images.githubusercontent.com/26858233/34646703-36e16608-f36f-11e7-809c-79cc93e6d17a.png)

For reference, the icon was not visible at all before commit https://github.com/nextcloud/server/pull/7478/commits/228ca16bea8a39d50c0085d04396713763cdb288 as before that commit the header overlapped the content wrapper; now it is positioned correctly, although the height does not fill the whole page.

Before:
![gallery-loading-firefox-highlight-before](https://user-images.githubusercontent.com/26858233/34646706-9b67209a-f36f-11e7-846d-1b879314d55e.png)

After:
![gallery-loading-firefox-highlight-after](https://user-images.githubusercontent.com/26858233/34646708-9cf7df3a-f36f-11e7-8517-885efa352db6.png)

@nextcloud/designers

**Comment by pixelipo** [comment]
Accidentally fixed in #366 :grin:
