### ISSUE TITLE
Share drop down in gallery is not properly shown

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/gallery#352]
There are some design issues with the share drop down shown for albums in the gallery:
-  The separator between share types is not shown
-  The information icons is slightly moved to the bottom
-  The social sharing* menu is moved to the top
-  The social sharing menu is slightly moved to the left

*The social sharing menu and toggle icon are shown only if at least [one of the social sharing apps](https://github.com/nextcloud/socialsharing) is enabled.

Share drop down in gallery:
![gallery-sharedropdown](https://user-images.githubusercontent.com/26858233/34649953-ef8efe88-f3b8-11e7-8e42-902da18ec93f.png)

Share drop down in slideshow (for reference, no issues here):
![gallery-slideshow-sharedropdown](https://user-images.githubusercontent.com/26858233/34649954-f1d27526-f3b8-11e7-85bc-dc89254fb46c.png)

The first three issues are caused by the rules for [.actions input, .actions button, .actions .button](https://github.com/nextcloud/gallery/blob/55dd75045d9261cbe77d41a5a0789749bd4bd3d3/css/upload.css#L19). As the share drop down in the gallery is a descendant of the actions bar its elements end being floats with no margins.

It is not possible to use `.actions :not(.shareDropDown) input, ...` to prevent the rules to be applied on the share drop down elements because if the element has any other ancestor before the share drop down that elements would match `:not(.shareDropDown)` and the rules will be applied anyway (see [last note](https://developer.mozilla.org/en-US/docs/Web/CSS/:not)).

Overriding the float rule with `.actions .shareDropDown input, ... { float: none; }` is easy, but the margin that is being overriding with `margin: 0;` depends on the element type. Moreover, overriding the margin again to restore the overridden value feels a little hacky and not very maintainable ;-) (for example, [the overridden margin for input elements comes from the server](https://github.com/nextcloud/server/blob/b248c53c6a8a2d420256921ca4889fc553ce8fee/core/css/inputs.scss#L42)).

Maybe it would be better to add another class to the inputs and buttons that are shown in the action bar so the problematic rules can be applied just to them? Or maybe cause the share drop down to be added as a sibling of the actions bar instead of a child of it? Please note that those are just untested ideas, I do not know what side effects they could have ;-)

Regarding the fourth issue it is just that [the social sharing menu is moved to the right only in the slideshow](https://github.com/nextcloud/gallery/blob/56f3d9c9c6256c6828cef60e80c506ec5fa3d616/css/share.css#L157).

@nextcloud/designers

**Comment by jancborchardt** [comment]
So I wonder if it's even warranted to put more work in the Gallery app regarding this, or if the work should rather be done on a proper grid view for the Files app. There we already have the sidebar and other elements like the sidebar tabs etc. Recreating this all in the old Gallery code seems unnecessary.

**Comment by MorrisJobke** [comment]
> So I wonder if it's even warranted to put more work in the Gallery app regarding this, or if the work should rather be done on a proper grid view for the Files app. There we already have the sidebar and other elements like the sidebar tabs etc. Recreating this all in the old Gallery code seems unnecessary and a lot of work.

Full ack.

**Comment by oparoz** [comment]
> So I wonder if it's even warranted to put more work in the Gallery app regarding this, or if the work should rather be done on a proper grid view for the Files app. There we already have the sidebar and other elements like the sidebar tabs etc. Recreating this all in the old Gallery code seems unnecessary and a lot of work.

It doesn't really matter if Files gets a grid view. A sidebar should be made available as a component so that any app can use it to let users perform basic actions such as sharing otherwise we end up with dozens of different implementations which will degrade the user experience of the product when using multiple apps.

**Comment by MorrisJobke** [comment]
> It doesn't really matter if Files gets a grid view. A sidebar should be made available as a component so that any app can use it to let users perform basic actions such as sharing otherwise we end up with dozens of different implementations which will degrade the user experience of the product when using multiple apps.

Correct - we started a ticket in the server repo for this: https://github.com/nextcloud/server/issues/7738

**Comment by danxuliu** [comment]
>  I wonder if it's even warranted to put more work in the Gallery app regarding this

For this specific issue, I say it is. It is not like changing the full implementation or making a complete redesign that will be thrown away. It is a menu that is out of place. It is right in front of the user, it looks bad, and it needs just a small fix.

Users do not care if in the future the gallery is going to use components provided by the server. They click the button, they see the menu out of place and they think "_Seriously? Haven't the developers noticed this? Or didn't they care? Meh..._" (OK, that is what a mean user would think; other users would say "_Yay! I found a bug! Let's report it so they can improve the app! :-D_" ;-) ).

**Comment by jancborchardt** [comment]
@danxuliu yeah, good point about this specific thing. In general though we should really focus on the grid view though. :)

@oparoz absolutely agree there, but that seems to take much more investment.
