### ISSUE TITLE
Sharing page header should follow the new layout introduced in Nextcloud 13

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/gallery#358]
[As currently the _master_ branch is compatible only with Nextcloud 13 and later](https://github.com/nextcloud/gallery/pull/347) the header shown in the sharing page should follow [the new layout introduced in Nextcloud 13](https://github.com/nextcloud/server/pull/6652).

Right now when the file list is being shown in the sharing page the new header is used, but when the _Toggle gallery_ button is clicked the new header is replaced with the old one.

@nextcloud/designers

**Comment by danxuliu** [comment]
Related issue in server: https://github.com/nextcloud/server/issues/6553

**Comment by MorrisJobke** [comment]
Time is up for this one -> 13.0.1

**Comment by MorrisJobke** [comment]
Will this be ready by later today or should we move it to 13.0.2? https://github.com/nextcloud/server/pull/8748

**Comment by juliushaertl** [comment]
Fix is in #425

**Comment by MorrisJobke** [comment]
Fixed with #425
