### ISSUE TITLE
Use new PublicPageResponse for sharing pages

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/gallery#403]
With https://github.com/nextcloud/server/pull/8051 we have a common public page template for NC14+ that should be used by apps to render public pages.

The PR also introduced two custom classes for rendering the direct link and add to my nextcloud menu entries, like in the screenshot below:
![bildschirmfoto vom 2018-01-25 20-39-27](https://user-images.githubusercontent.com/3404133/35408733-76f16734-0210-11e8-9598-0d5891c32a18.png)

The question is if we should just used those classes from the files_sharing app:
- OCA\Files_Sharing\Template\ExternalShareMenuAction
- OCA\Files_Sharing\Template\LinkMenuAction

Since the gallery app in bundled with the NC releases right now I see no problem that those are not part of the public API right now. Anyway it isn't that nice so we should probably also move them to the OCP namespace. Until now it seems the gallery app has copied the code that is required from files_sharing, but that doesn't seem to be a good solution to me as well. Any thoughts on that?

WIP branch: https://github.com/nextcloud/gallery/tree/public-page-response

**Comment by juliushaertl** [comment]
@oparoz How does gallery handle being dependent on files_sharing at the moment? It seems to be using just its config values. Would be using the classes from OCA\Files_Sharing in gallery an option?

**Comment by oparoz** [comment]
I've always been told that apps should be completely independent from core, so for that reason, we always recreate all the JS files in Gallery.
This may change once we have some re-usable components in the core.

**Comment by desaintmartin** [comment]
Hello,
Is there any update on this? I'm afraid it still completely destroys the public pages of Gallery app...
