### ISSUE TITLE
Owncloud Gallery - Beta access to create thumbnails via OCC command line

### ISSUE THREAD

**Issue by vcisel** [nextcloud/gallery#409]
## Feature request
https://github.com/owncloud/gallery/wiki/Create-Thumbnails

### Steps to reproduce
`sudo -u apache  ./occ gallery:create-thumbnails --all`

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "gallery" namespace.

### Expected behaviour

Would it be possible to have access to the command line tool even if this is not yet in production?
Is it really not stable at all? Is there a way to enable the beta feature from the master branch?
I would be happy to test it...

**Comment by kprkpr** [comment]
Please do not ignore it... Thumbnail and gallery is the most slow process in NC as 2019 compared with other tools..

**Comment by skjnldsv** [comment]
See the preview generator app now
