### ISSUE TITLE
"Switch to file list" button is taller than it should be

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/gallery#413]
This is a regression introduced by a change in the server (commit nextcloud/server@966ceca8eaf9d06d9f0528c83168a2942ca7e279). The problem is that since that commit CSS rules (and, specifically, the `height` rule) for `#controls .button` are applied to `#controls > .button`, but the _Switch to file list_ button does not match that selector and thus ends with a wrong height:
![gallery-button-filelist-height](https://user-images.githubusercontent.com/26858233/37744495-c5ef076c-2d6f-11e8-8d85-dc2dafd86492.png)

@nextcloud/designers

**Comment by skjnldsv** [comment]
I'm so tired of the gallery app! ^^
Let me fix this!
