### ISSUE TITLE
LIKE annotation for shared photos

### ISSUE THREAD

**Issue by yassinchabeb** [nextcloud/gallery#422]
## Feature request
LIKE annotation for shared photos
**User type**: Logged-in

**User level**: Beginners

### Description

people who can see the photo can like it (LIKE annotation for shared photos)
### Benefit / value

Just keep liked photo and delete others for example
### Risk / caveats

no risk
### Sponsorship

**Are you a developer willing to implement this feature?**: no

**Can you sponsor the development of this feature or do you know someone who can?**: no

**Comment by blacs30** [comment]
I was looking for a feature like this for long time. I think some similar feature request existed already but wasn't able to find it now.

**Use case on my side:**
Share pictures from a photo shooting with the model, the model can star pictures he/she likes and then the retouching can begin. Without that feature it's currently writing down the filename of the picture and communicating it back but that's little bit old school.

**Comment by under-score** [comment]
great idea. First right click triggers a star symbol and sends filename via ajax to a flat file on the server, second click removes everything. And we are all happy again.

**Comment by ryanjk333** [comment]
I have the exact same use case as @blacs30 .  Would it be possible to implement something like this?

**Comment by skjnldsv** [comment]
Are we talking about `like`, like in facebook "likes" ?

**Comment by ryanjk333** [comment]
We're talking about the star feature that's already implemented in other views and looking to see if that star can be available when photos are being viewed at full screen in the gallery. Basically, what's the best way to star an image when browsing the images at full screen in the gallery? Right not there isn't a good way to do it without exiting image slide show view.

**Comment by skjnldsv** [comment]
So favouriting then.
So if I get this right, you want the option to favourite a picture from the slideshow? Why is there mentions of the world "annotation" on the first post?
Are you sure that is what @yassinchabeb meant? :)

**Comment by ryanjk333** [comment]
Correct! Good question, perhaps this request was more what was being asked in the other thread that was just closed. Is this something that can easily be implemented?

**Comment by under-score** [comment]
any update here?
