### ISSUE TITLE
Panorama viewer

### ISSUE THREAD

**Issue by oparoz** [nextcloud/gallery#43]
_From @oparoz on July 26, 2015 14:58_

_User requested_

Some people would like to be able to view panorama or photo sphere images such as the ones taken by a mobile phone.

I know bigshot supports VR images. Not sure what it would take to implement...
##

_Copied from original issue: owncloud/gallery#234_

**Comment by oparoz** [comment]
_From @setnes on August 29, 2015 14:15_

I was thinking about this when we worked on the image preview size logic that was based on the monitor size.  Even without a fancy VR viewer, panoramas might be better viewed if they could simply be zoomed and scrolled.  Right now we decide the longest image edge for the preview size based on the longest monitor edge plus a normalization fudge of 100.  For a panorama, requesting a larger image (make the shortest image edge match the longest monitor edge) might have an advantage... but it could end up being a very large file served.  It seems like it should be a second download.  

The ratio between image length and width could drive this.  If it was over a certain threshold (maybe one edge has to be more than twice as long as the other), we could treat it as a panorama.  I don't think we have the image dimensions at the time we are requesting the preview though.

Just thoughts...

**Comment by oparoz** [comment]
If we automatically download the HD pictures when zooming in (https://github.com/owncloud/gallery/issues/193). We could keep things as-is and users would get the full res image as soon as they zoom-in and could then pan left-right.

Would that be good enough?

**Comment by oparoz** [comment]
_From @jospoortvliet on August 31, 2015 9:12_

@oparoz for panorama's - I think it's fine... Sure, the whole parallax thing is fancy but not really crucial.

**Comment by TheNetStriker** [comment]
I would like to view pictures from my Galaxy Gear 360 in the owncloud gallery. Because those are real 360 Photoshpere pictures it get's distorted when zooming in. I found three javascript viewers for such photos:

http://photo-sphere-viewer.js.org/
https://pannellum.org/
https://developers.google.com/vr/concepts/vrview-web

Could any of those viewers be implemented in the owncloud gallery?

**Comment by beat** [comment]
:+1: that would be awesome!

**Comment by BloodyIron** [comment]
What's it going to take to get photosphere support? Or for 360 videos? I have photos from events I've taken and I really do need to be able to check them out in nextCloud!

**Comment by jospoortvliet** [comment]
Somebody will have to do the work of implementing one of the javascript viewers into the Nextcloud Gallery... 'somebody' -> can be anyone who feels like doing it... Alternatively, a company could decide to pay somebody to do it.

**Comment by TheNetStriker** [comment]
I've got some experience with web applications, but I'm unfamiliar with nextcloud addons. The Pannellum viewer is very easy to integrate because the images do not have to be pre processed in some form. A better integration would be to use Marzipano, but that library requires pre processed tiles.

Maybe I would be able to implement a viewer if someone could tell me where to start. For instance I would have to know how to identify which pictures are panorama pictures. Is it possible to get the exif information from the current picture in the gallery code?

**Comment by oparoz** [comment]
> Is it possible to get the exif information from the current picture in the gallery code?

This is a component which is missing from our core product and which prevents quite a few features from being delivered.
It's on the roadmap, but until we have EXIF data in the database, we can't easily implement this as it would slow down galleries each time we enter an album and have to extract EXIF data again.

**Comment by BloodyIron** [comment]
So, any chance we could see this added? I love taking photospheres at events I go to, and I really want to explore them in Gallery.

Please? :)

**Comment by R0Wi** [comment]
Hey guys, i've made a little Nextcloud-App for integrating photo-sphere-viewer.js. So actually the app will be opened by clicking on a .jpg-file, which has a prefix "PANO".

Check it out. Looking forward to hear your feedback :-)

[https://github.com/R0Wi/Nextcloud-PhotoSphereViewer](https://github.com/R0Wi/Nextcloud-PhotoSphereViewer)
[https://apps.nextcloud.com/apps/photosphereviewer](https://apps.nextcloud.com/apps/photosphereviewer)

**Comment by TheNetStriker** [comment]
I've just testet this and it works very well with my Samsung Photosphere photos if I rename them. The only thing I'm missing is that I can't quickly switch to the next and previous photo in the current folder. I have to go back to the file viewer and click the next photo to view it as a Photosphere. Also when viewing the photos in the gallery app the Photosphere viewer does not start and the photo is displayed like a normal photo.

**Comment by sbrl** [comment]
Works a treat. Thanks,  @R0Wi :smiley_cat:

**Comment by BloodyIron** [comment]
Any chance we can get this into the Gallery part? And perhaps mainlined? :)

**Comment by R0Wi** [comment]
Fully integrating the viewer into the gallery app would be the next step, but this requires more investigation. Especially i would have to touch some parts of the gallery app code.

@BloodyIron Of course i keep on working towards mainline dev, it was just a first approach for the moment :-)

**Comment by sbrl** [comment]
It's a fantastic first step and workaround, @R0Wi :D

**Comment by MichaelKorn** [comment]
Thx. It is working fine with pictures from Gear 360.

**Comment by skjnldsv** [comment]
Superseded by https://github.com/nextcloud/gallery/issues/540 and https://github.com/nextcloud/files_photospheres/issues/27
