### ISSUE TITLE
Add an alias for .nomedia

### ISSUE THREAD

**Issue by midorlo** [nextcloud/gallery#438]
### Description

Not a bug. 

Using a `.nomedia` file to prevent _Gallery_ from indexing your music folder has bad consequences for various music collection managing and playback softwares. As a prominent example (which I do not endorse in any way) _GooglePlayMusic_ will refuse to re-/index the corresponding folder.

## Feature request

Decide for a filename and implement it an alias for `.nomedia` to be recognised by _Gallery_.  `.nopicture` and `.noimage` may be good candidates, since they are (afaik) used by AOSP Gallery and probably some other Apps for Android.

**Comment by oparoz** [comment]
Not a bad idea :)

**Comment by tnyeanderson** [comment]
I should have a PR for this by the end of the week. I will add the alias `.noimage`, but `.nomedia` will continue to work as well. I can't find any other apps that use `.nopicture`, but it would be trivial to add once I have the basic alias code set up.

**Comment by tnyeanderson** [comment]
This is done.

#520
