### ISSUE TITLE
Gallery is pulling up all manner of non-image files, why and how to prevent this?

### ISSUE THREAD

**Issue by ASmith-** [nextcloud/gallery#442]
**Gallery is pulling up all manner of non-image files and attempting to display them. Why and how to prevent this?**

Gallery is attempting and Failing to display documents, mp4 videos and all manner of non-image files. Why is Gallery automatically on its own attempting to pull up non-image files and display them?

How do I order the Gallery tool to only pull up the well known, popular image extensions only?

**Comment by oparoz** [comment]
It shouldn't do that. A list is defined in the code to avoid pulling any data which cannot be displayed in Gallery.

It would be nice if you could provide some proof/logs to back your statement.

**Comment by ASmith-** [comment]
Defined in the Code, wow that's descriptive. Do you have the exact path, folder, file name where that definition of precisely, explicitly what image files Gallery is allowed to pull up?

**Comment by ASmith-** [comment]
Ok, I'll go in and weed out the files the Gallery tool is pulling out of what appears to be a full scale scan of all shared folders that shouldn't be attempted to be displayed. A enhancement if this tool doesn't already have this ability would be to narrow the scan of what folders to display media from. I have right at 1 million files in shared files and it looks like the Gallery tool is looking at the larger forest of everything shared to pull up and display instead of a administrative focus on specific folders to scan and display if there's any image files in them.
