### ISSUE TITLE
Show thumbnails for non-image files (pdf,doc,etc)

### ISSUE THREAD

**Issue by Gatak** [nextcloud/gallery#461]
It would be great if the gallery could display thumbnails and previews for non-image files like PDF.

Clicking. The large preview could load the built in PDF reader or offer user to download.

Previews are already being generated so I think it would be possible to use them.
![screenshot_20180813-225631_opera](https://user-images.githubusercontent.com/1469150/44057837-9752d592-9f4c-11e8-992f-6df780bc82cd.jpg)
![screenshot_20180813-225758_opera](https://user-images.githubusercontent.com/1469150/44057847-9c5e51ec-9f4c-11e8-9282-8182e4a7b1c9.jpg)

**Comment by oparoz** [comment]
This is by design. The goal is to present pictures in a photowall.
You probably want something like a gridview in the Files app and that's coming.

**Comment by Gatak** [comment]
You're right.It is. I thought that was a gallery apps responsibility (grid view of files).
