### ISSUE TITLE
Feature Request: Custom Sortorder

### ISSUE THREAD

**Issue by galla-placidia** [nextcloud/gallery#471]
# Feature request

**User type**: Logged-in and public user

**User level**: Beginners, intermediate and advanced

## Description
I would like to sort my photos in the list to bring it to an contextual order.
At the moment I have to think about contextual filenames to have at least the chance to sort it by alphabet.

## Benefit / value
At the moment I have to think about contextual filenames to have at least the chance to sort it by alphabet.

## Sponsorship

**Are you a developer willing to implement this feature?**:  no

**Can you sponsor the development of this feature or do you know someone who can?**: sorry no

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.
