### ISSUE TITLE
Tab "view recent" is empty

### ISSUE THREAD

**Issue by GekoCH** [nextcloud/gallery#472]
At the beginning of using Nextcloud v13.0.6 the "view recent" tab did work great.
Now after uploading around 1 TB of data the tab does show nothing. The "pls wait" icon appears but nothing gets displayed afterwards.

![image](https://user-images.githubusercontent.com/3285638/45809995-e6b6fb00-bcc9-11e8-9e23-2c2b7cb32893.png)

Andy

**Comment by skjnldsv** [comment]
Unrelated to gallery
