### ISSUE TITLE
Enhancement: click to delete picture directly from picture wall

### ISSUE THREAD

**Issue by klepptor** [nextcloud/gallery#479]
Sometimes the thumbnail in the picturewall is already sufficient to decide to delete a picture.

Maybe it's possible to add a trash bin button to the thumbnails...

**Comment by CrustyApplesniffer** [comment]
I agree. As a user I should be allowed to delete a picture from the wall view.
I would like to have a checkbox to select multiple files and to delete them.

**Comment by skjnldsv** [comment]
Same as #448 
I think the ui should be clear of any marks to focus on the pictures. @jancborchardt ?

**Comment by jancborchardt** [comment]
@skjnldsv absolutely, there should be nothing covering the pictures. :)
