### ISSUE TITLE
Possible to exclude file type from slideshow?

### ISSUE THREAD

**Issue by Atlantis1979** [nextcloud/gallery#487]
Just wondering if it's possible to exclude a certain file type from the slideshow function?
We're having an issue with huge TIFF files not being rendered, so would like to exclude Gallery from even acknowledging them so they don't mess up slideshows for our users.

Thanks.

**Comment by skjnldsv** [comment]
Closing as outdated.
Once #540 is merged, tiff won't be supported by default until https://github.com/nextcloud/viewer/issues/229 is integrated. Nonetheless since we're now using previews there, if you pre-generate tiff ones with the preview generator, you should not get any issues.
