### ISSUE TITLE
Tiles get covered

### ISSUE THREAD

**Issue by bertwesarg** [nextcloud/gallery#498]
# Bug report

## Steps to reproduce

1. Open Gallery App with many tiles
1. Resize browser window, so that tiles get covered on the right side

## Expected behaviour
All tiles are always shown in full, never leave partially the window

## Actual behaviour
Tiles move out of the window, and thus are not visible anymore. One could 

![nextcloud-gallery-covered-tiles](https://user-images.githubusercontent.com/111934/52331007-4ef74680-29f7-11e9-90cd-e85e5dca3186.png)

While not on the picture, there is only a minimal vertical scrollbar, to scroll the amount of the horizontal scrollbar, and vice versa.

## Server configuration

**Operating system**: Debian Buster 32bit

**Web server:** nginx

**Database:** MariaDB

**PHP version:** 7.3

### Nextcloud configuration

**Nextcloud version:** 15.0.2

**Updated from an older installation or fresh install:** from 15.0.0

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using custom gallery.cnf config files:** no

## Client configuration

**Browser:** Firefox 65

**Operating system:** Ubuntu Mate 18.04 64bit

**Comment by langfingaz** [comment]
Duplicate of this issue: https://github.com/nextcloud/gallery/issues/494
If you don't mind, I would suggest to continue discussing it over there.

Greetings, Daniel

**Comment by bertwesarg** [comment]
Absolutely!

**Comment by bertwesarg** [comment]
Close as duplicate
