### ISSUE TITLE
JS vulnerabilities in third party libraries

### ISSUE THREAD

**Issue by bavay** [nextcloud/gallery#516]
# Bug report
Several of the JavaScript library used by the gallery have known vulnerabilities and should be updated (as seen in the JS Console as well as with the retire.js Firefox extension):
DOMPurify 0.8.6, handlebars.js 4.0.5, jquery-ui-dialog 1.10.0 and jquery 2.1.4.

Actually, DOMPurify 1.0.4 is used somewhere else in the Gallery app, so it could be interesting to also use it instead of version 0.8.6 everywhere.

**Comment by skjnldsv** [comment]
Fixed now
