### ISSUE TITLE
PDF to PNG conversion - can this be configured to generate JPG instead?

### ISSUE THREAD

**Issue by james-cook** [nextcloud/gallery#521]
I assume (?) gallery is the right place for this. 
For various reasons I can't change the ImageMagick on this server - version 6.8.9-9.
This version of ImageMagick has a known bug reading PNGs and reports "corrupt image" on the surface (the PNGs are not corrupt).
So I'm wondering if I can configure the PDF conversion to generate jpgs instead of pngs

**Comment by skjnldsv** [comment]
Sorry, this is not the right place for it.
So I would like to ask you to raise your question in the forums: https://help.nextcloud.com :)
