### ISSUE TITLE
thumbnail generation stops

### ISSUE THREAD

**Issue by kylepwarren** [nextcloud/gallery#524]
thumbnail generation in semi-large(not really that large) folders hangs. I don't know the exact number of photos I scroll through before I stop seeing thumbnails, probably around 200 or 300. Does anyone have any insight into what[typically] is causing the generation to stop? I'd be happy to help, but imagine some people already have ideas about what's causing it, would like to not start from scratch.

**Comment by kylepwarren** [comment]
I just scrolled through a large photo folder in gallery view *on a newer computer* and the performance was much better(though it did eventually get much, much slower) - making me think maybe TOO much is being asked of the client/browser. Is virtual scroll an option, i.e. just load a few pages worth of pictures at a time, not thousands? I'm not 100% certain, but it really seems like a browser performance issue

**Comment by skjnldsv** [comment]
Hey this is probably coming fro your setup.
Hello!
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>
