### ISSUE TITLE
Display of the file formats which are also displayed by the Viewer

### ISSUE THREAD

**Issue by grenzverkehr** [nextcloud/gallery#535]
Gallery should display all file formats that Viewer (https://github.com/nextcloud/viewer) also displays. So far these are pictures and videos. Later audio, PDF, text etc. will be added. Furthermore, for the slideshow also Viewer should be used.

**Comment by skjnldsv** [comment]
Hey!

Thanks for your feedback ! :)
Gallery will aim to be photo-oriented utility.

We will support what the default viewer supports, meaning pictures and videos.
Anything else is out of scope :)
