### ISSUE TITLE
Exception in Log when link to share is expired 

### ISSUE THREAD

**Issue by frlan** [nextcloud/gallery#565]
# Bug report

## Steps to reproduce

1. Create a shared link from gallery
2. Delete link
3. Try to access the link

## Expected behaviour
This should result in a 404 and not giving an exception inside logs

## Actual behaviour
 {"reqId":"HXJ6cVFRxNdvbd8cLUL1","level":3,"time":"2020-01-18T21:12:27+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"--","app":"gallery","method":"GET","url":"\/apps\/gallery\/s\/Woy94HDXpGAatGw","message":"Exception: The requested share does not exist anymore (404)","userAgent":"Synapse\/1.8.0rc1 xxxx","version":"17.0.2.1"}

**Comment by jancborchardt** [comment]
Gallery was replaced by the new Photos app → please upgrade. :) https://github.com/nextcloud/photos
