### ISSUE TITLE
:skull: Gallery was replaced by :camera_flash: Photos

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/gallery#567]
:skull: The gallery app has been replaced by the beautiful new app: :camera_flash: Nextcloud Photos - Your memories under your control

Before reporting an issue or opening a pull request, please checkout the new app and see if your request still needs to be handled there. In case it is, open your PR against the photos app.

**Comment by jancborchardt** [comment]
The only thing to resolve before archiving this repository seems to be what we do with the issues which have bounties attached to it:
https://github.com/nextcloud/gallery/issues?q=is%3Aopen+is%3Aissue+label%3Abounty

- Some of them are solved by Photos already (e.g. "Show favorites") → They could be closed and claimed to be redistributed towards issues in Photos
- Some we definitely want in the photos app as well and it would be nice to reward whoever implements it. → We could wait with archiving this and then close+claim those once it’s done.
- Not sure if moving the issues to another repository keeps the bounty. Kind of related FAQ: https://github.com/bountysource/core/wiki/Frequently-Asked-Questions#what-happens-if-an-issue-ive-backed-is-closed-without-resolution

cc @rullzer @skjnldsv @jospoortvliet

**Comment by nickvergessen** [comment]
We can't archive until the last 17 version is out, because otherwise oushing the tag and potential fixes fails hard

**Comment by J0WI** [comment]
> First, a final reminder that with the availability of Nextcloud Hub v20 we ceased maintenance of Nextcloud 17.

https://nextcloud.com/blog/20-0-1-is-here-with-about-60-changes-get-your-update/
