### ISSUE TITLE
File list refreshes after closing Gallery slideshow

### ISSUE THREAD

**Issue by oparoz** [nextcloud/gallery#71]
_From @jancborchardt on September 8, 2015 13:22_

1. Open an image with the Gallery slideshow / detail view
2. Close it again

Expected:
You are able to seamlessly browse your pics again.

What actually happens:
The whole file list is very visibly reloaded. That’s confusing and rips you out of the flow.

@oparoz @schiesbn @PVince81 @MorrisJobke what can we do here? Same is true for the text editor cc @tomneedham

_Copied from original issue: owncloud/gallery#313_

**Comment by MorrisJobke** [comment]
Duplicate of #72

**Comment by oparoz** [comment]
Thanks :)
