### ISSUE TITLE
Add transifex

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/gallery#9]
for myself

**Comment by oparoz** [comment]
Do we merge translations or will those come exclusively from our translators?

**Comment by MorrisJobke** [comment]
> Do we merge translations or will those come exclusively from our translators?

What do you mean? They will be done on transifex and the bot pushes them directly into the repo.

**Comment by oparoz** [comment]
I meant from oC, but you've replied to my question :)

**Comment by MorrisJobke** [comment]
> I meant from oC, but you've replied to my question :)

Ah. It is bootstrapped with the current translation and then everything will be updated only by our translators.
